### ISSUE TITLE
Windows build doesn't work

### ISSUE THREAD

**Issue by graphixillusion** [jack5341/super-dollop#13]
Hi there. As stated, here's what happens when you start the binary under Windows 10 x64:

```
panic: Endpoint:  does not follow ip address or domain name standards.

goroutine 1 [running]:
github.com/jack5341/super-dollop/pkg.Connect()
        /home/runner/work/super-dollop/super-dollop/pkg/minio.go:18 +0xa7
github.com/jack5341/super-dollop/cmd.Execute()
        /home/runner/work/super-dollop/super-dollop/cmd/root.go:21 +0x19
main.main()
        /home/runner/work/super-dollop/super-dollop/main.go:8 +0x17
```

**Comment by jack5341** [comment]
Thank you for your Issue!

Looks like there is a problem with your environments can you show them?

**Comment by graphixillusion** [comment]
@jack5341 i didn't set any env. i would like to use this only for encrypting/decrypting purpose, without the minio/s3 stuff.
